openapi: 3.0.0
info:
  title: Altcode Website
  description: Altcode Website API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server

paths:
  /auth/signup:
    post:
      tags:
        - Authorisation
      requestBody:
        description: Create new user
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
                avatar:
                  type: string
                  format: binary
      responses:
        "201":
          description: new user created successfully
  /user/login:
    post:
      tags:
        - Login
      requestBody:
        description: user authorization
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: login successful
